version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo Building the Docker image... 
      - sudo docker info           
      - docker build -t demo/samplerepo .
      - docker tag demo/samplerepo:latest 454143665149.dkr.ecr.us-east-2.amazonaws.com/demo/samplerepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 454143665149.dkr.ecr.us-east-2.amazonaws.com/demo/samplerepo:latest
artifacts:
  files:
    - target/messageUtil-1.0.jar